name: Task
description: Use this template for project tasks
title: "[Task]: "
labels: ["task"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: Describe the goal of this task.
      placeholder: "Explain the outcome this task should achieve."
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Checklist items for this task
      placeholder: "- [ ] Item 1"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define what must be true to consider this task done
      placeholder: "- [ ] Criterion 1"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: outofscope
    attributes:
      label: Out of scope
      description: Define what is NOT part of this task
      placeholder: "What is explicitly excluded from this task?"
