// src/shared/bindings/loggerBindings.js
// Thin wrapper around Go Zap logger bindings generated by Wails.
// Keeps frontend decoupled from internal Go package paths.
//
// If Go bindings change in the future, only this file needs updating.

import { Info, Warn, Error, Debug } from "@wailsjs/go/wailsapp/LoggerBridge"

export const loggerBindings = {
  info: Info,
  warn: Warn,
  error: Error,
  debug: Debug,
}
