// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1:string,arg2:string):Promise<void>;

export function Error(arg1:string,arg2:string):Promise<void>;

export function Info(arg1:string,arg2:string):Promise<void>;

export function Warn(arg1:string,arg2:string):Promise<void>;
