name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  go-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      # Ensure //go:embed finds at least one file under frontend/dist
      - name: Prepare embed assets (placeholder)
        run: |
          mkdir -p frontend/dist
          test -f frontend/dist/index.html || printf '<!doctype html><html><head><meta charset="utf-8"><title>placeholder</title></head><body><div id="app"></div></body></html>' > frontend/dist/index.html

      - name: Go vet
        run: go vet ./...

      - name: Go test
        run: go test ./... -v
