name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  go-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Prepare embed assets (placeholder)
        run: |
          mkdir -p frontend/dist
          test -f frontend/dist/index.html || cat > frontend/dist/index.html <<'HTML'
          <!doctype html><html><head><meta charset="utf-8"><title>placeholder</title></head>
          <body><div id="app"></div></body></html>
          HTML

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -v
